name: mansur_sarkhanov
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  video_player: ^2.8.3
  responsive_framework: ^1.4.0
  fl_chart: ^0.62.0
  flutter_svg: ^2.0.5
  lottie: ^3.1.0
  firebase_core: ^2.27.2
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Icons/
    - assets/Lottie/
